#-                                                                                                                                                                                                                                                                                                                [218/1103]# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2020 Hesham Almatary
#
# This software was developed by SRI International and the University of
# Cambridge Computer Laboratory (Department of Computer Science and
# Technology) under DARPA contract HR0011-18-C-0016 ("ECATS"), as part of the
# DARPA SSITH research programme.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#


def configure(ctx):
    print("Configuring severs Demo @", ctx.path.abspath())

    ctx.env.append_value('INCLUDES', [
        ctx.path.abspath(),
        ctx.path.abspath() + "/TraceMacros/Example1",
        ctx.path.abspath() + "/DemoTasks/include",
        ctx.path.abspath() + "/Common/FreeRTOS_Plus_TCP_Demos/include",
        ctx.path.abspath() + "/Common/FreeRTOS_Plus_CLI_Demos/include",
        ctx.path.abspath() + "/Common/Utilities/include",
        ctx.path.abspath() + "/Common/Demo_IP_Protocols/include"
    ])

    ctx.env.append_value('DEFINES', [
        'configPROG_ENTRY                   = main_servers',
        'mainCREATE_HTTP_SERVER             = 1',
        'ipconfigUSE_HTTP                   = 1',
        'ipconfigUSE_FTP                    = 1',
        'ipconfigUSE_FAT_LIBDL              = 1',
        'ffconfigMAX_FILENAME               = 1',
        'configHTTP_ROOT                    = "/ram/websrc/"',
        'configUSE_NET_VIRTIO               = 1',

        '_STAT_H_                           = 1',
        'configCOMPARTMENTS_NUM             = 0',
        'configMAXLEN_COMPNAME              = 32'
    ])

    ctx.env.append_value(
        'LIB_DEPS',
        ['freertos_tcpip', 'freertos_cli', 'freertos_libdl', 'freertos_fat', 'virtio'])


def build(bld):
    name = "main_servers"

    print("Building main_servers Demo")

    bld.stlib(
        features=['c'],
        source=[
            bld.path.parent.find_resource('TCPEchoClient_SingleTasks.c'),
            bld.path.parent.find_resource('SimpleUDPClientAndServer.c'),
            bld.path.parent.find_resource('SimpleTCPEchoServer.c'),
            bld.path.parent.find_resource('main_servers.c'), 'CLI-commands.c',
            'Common/FreeRTOS_Plus_FAT_Demos/CreateAndVerifyExampleFiles.c',
            'Common/FreeRTOS_Plus_FAT_Demos/test/ff_stdio_tests_with_cwd.c',
            'Common/FreeRTOS_Plus_CLI_Demos/TCPCommandConsole.c',
            'Common/FreeRTOS_Plus_CLI_Demos/UDPCommandConsole.c',
            'Common/FreeRTOS_Plus_CLI_Demos/File-related-CLI-commands.c',
            'Common/Demo_IP_Protocols/FTP/FreeRTOS_FTP_server.c',
            'Common/Demo_IP_Protocols/FTP/FreeRTOS_FTP_commands.c',
            'Common/FreeRTOS_Plus_TCP_Demos/TFTPServer.c',
            'Common/Demo_IP_Protocols/Common/FreeRTOS_TCP_server.c',
            'Common/Demo_IP_Protocols/HTTP/FreeRTOS_HTTP_commands.c',
            'Common/Demo_IP_Protocols/HTTP/FreeRTOS_HTTP_server.c',
            'TraceMacros/Example1/DemoIPTrace.c'
        ],
        use=[
            "freertos_core_headers", "freertos_bsp_headers", "freertos_tcpip_headers", "freertos_cli_headers",
            "freertos_libdl_headers", "freertos_fat_headers", "virtio_headers", "cheri_headers"
        ],
        target=name)
